-- MySQL Script generated by MySQL Workbench
-- Fri Sep 12 17:24:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `id_professor` INT NOT NULL,
  `Nome_professor` VARCHAR(45) NULL,
  `Materia` VARCHAR(45) NULL,
  PRIMARY KEY (`id_professor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Turma` (
  `id_turma` INT NOT NULL,
  `Professor_id_professor` INT NOT NULL,
  PRIMARY KEY (`id_turma`, `Professor_id_professor`),
  INDEX `fk_Turma_Professor_idx` (`Professor_id_professor` ASC) VISIBLE,
  CONSTRAINT `fk_Turma_Professor`
    FOREIGN KEY (`Professor_id_professor`)
    REFERENCES `mydb`.`Professor` (`id_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
  `id_aluno` INT NOT NULL,
  `Nome_aluno` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Turma_id_turma` INT NOT NULL,
  `Turma_Professor_id_professor` INT NOT NULL,
  PRIMARY KEY (`id_aluno`, `Turma_id_turma`, `Turma_Professor_id_professor`),
  INDEX `fk_Aluno_Turma1_idx` (`Turma_id_turma` ASC, `Turma_Professor_id_professor` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_Turma1`
    FOREIGN KEY (`Turma_id_turma` , `Turma_Professor_id_professor`)
    REFERENCES `mydb`.`Turma` (`id_turma` , `Professor_id_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Atividade` (
  `id_atividade` INT NOT NULL,
  `Materia` VARCHAR(45) NULL,
  `Professor` VARCHAR(45) NULL,
  PRIMARY KEY (`id_atividade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Turma_has_Atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Turma_has_Atividade` (
  `Turma_id_turma` INT NOT NULL,
  `Turma_Professor_id_professor` INT NOT NULL,
  `Atividade_id_atividade` INT NOT NULL,
  PRIMARY KEY (`Turma_id_turma`, `Turma_Professor_id_professor`, `Atividade_id_atividade`),
  INDEX `fk_Turma_has_Atividade_Atividade1_idx` (`Atividade_id_atividade` ASC) VISIBLE,
  INDEX `fk_Turma_has_Atividade_Turma1_idx` (`Turma_id_turma` ASC, `Turma_Professor_id_professor` ASC) VISIBLE,
  CONSTRAINT `fk_Turma_has_Atividade_Turma1`
    FOREIGN KEY (`Turma_id_turma` , `Turma_Professor_id_professor`)
    REFERENCES `mydb`.`Turma` (`id_turma` , `Professor_id_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turma_has_Atividade_Atividade1`
    FOREIGN KEY (`Atividade_id_atividade`)
    REFERENCES `mydb`.`Atividade` (`id_atividade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
